### ISSUE TITLE
PhantomJS does not support Object.assign

### ISSUE THREAD

**Issue by SimonSchick** [WatchBeam/beam-interactive-node#13]
This is relevant as the prerender service uses this function and therefor fails.
Please shim or replace with something.

Main problem is [here](https://github.com/WatchBeam/beam-interactive-node/blob/91f5daf4e0d7f056584e5c52ddbf3b3ca9d05859/lib/errors.js)

**Comment by ProbablePrime** [comment]
#14 fixed this, so can probably be closed.
